export const GET_STOCKLIST = "GET_STOCKLIST" 
export const UPDATE_STOCKLIST = "UPDATE_STOCKLIST"

export const TOGGLE_STOCK = "TOGGLE_STOCK"
export const RESET_HISTORY = "RESET_HISTORY"

export const UPDATE_CONNECTION = "UPDATE_CONNECTION"